baseURL: https://www.shagunjhaver.com/
title: Shagun Jhaver
theme: ah-hugo
languageCode: en
paginate: 20
disqusShortname: shagunjhavercom
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    style: "monokai"
disableKinds: ["RSS"]
buildFuture: true

permalinks:
  blog: "/blog/:year/:month/:day/:slug/"
  tags: "/blog/tags/:slug/"  # https://www.hannaliebl.com/blog/nesting-taxonomies-in-hugo/
  year: "/blog/:slug/"
  month: "/blog/:slug/"

# Create year/month archives with taxonomies:
# https://discourse.gohugo.io/t/how-to-generate-chronological-blog-archives-in-hugo/13491/6
# Requires (1) taxonomy definition here, (2) permalink definition, and (3) this in each post's metadata:
#   year: "2020"
#   month: "2020/11"
taxonomies:
  tag: tags
  research_type: research_type
  year: year
  month: month

params:
  author: Shagun Jhaver 
  minibio: Social computing, CSCW, HCI, platforms, internet studies
  description: "Shagun Jhaver is an assistant professor at Rutgers University, researching user-algorithm interactions."
  research_order: [peer-reviewed-article, technical_report, workshop-papers-and-panel, thesis]
  social:
    twitter: shagunjhaver 
    facebook: shagun.jhaver 
  images:
  - profiles/twitter-card-large.png
  feedIcon: profiles/square-bg.png
  orcid: 0000-0002-6728-7101
  pgp:
    key: pgp_ath.asc.txt
    fingerprint: 4AA2 FA83 A8B2 05A4 E30F<br /> 610D 1382 6216 9178 36AB
  dateFormat: January 2, 2006
  blogPostDateFormat: Monday, January 2, 2006
  since: 2007
  googleanalytics: "UA-527449-5"
  github_repo: https://github.com/shaguniitb/ath-hugo
  little_links:
    - icon: fa fa-envelope
      name: E-mail
      url: "mailto:shagun.jhaver@rutgers.edu"
      weight: 1
    - icon: fab fa-medium
      name: Medium
      url: "https://medium.com/@shagunjhaver"
      weight: 2      
    - icon: ai ai-google-scholar
      name: Google Scholar
      url: https://scholar.google.com/citations?user=OgtKT6UAAAAJ
      weight: 3      
    - icon: ai ai-acmdl-square
      name: ACM Digital Library
      url: https://dl.acm.org/author_page.cfm?id=99658987207
      weight: 4
    - icon: fab fa-github
      name: GitHub
      url: https://github.com/shaguniitb
      weight: 5                        
    - icon: fab fa-twitter
      name: Twitter
      url: https://twitter.com/shagunjhaver
      weight: 6
    - icon: fab fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/shagun-jhaver/
      weight: 8

menu:
  main:
    - name: About
      url: /
      weight: 1
    - name: Research
      url: research/
      weight: 3
    - name: Teaching
      url: teaching/
      weight: 4      
    - name: News
      url: news/
      weight: 6
    - name: Now
      url: now/
      weight: 7
    - name: Social Computing Lab
      url: lab/
      weight: 8      


mediaTypes:
  "application/atom+xml":
    suffixes: ["xml"]

outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
  atom:
    mediaType: "application/atom+xml"
    baseName: "atom"
    suffix: "xml"
    isHTML: false
    isPlainText: false
    rel: "alternate"

outputs:
  home: 
    - "html"
    - "jsonfeed"
    - "atom"
  page:
    - "html"

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
